spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abishekaryal070@gmail.com
    password: wmkw lfsc guvd kcfz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
    contexts: dev
  application:
    name: inventorymgmt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/inventorymgmt_db'
    username: root
    password: Abishek60@
    jpa:
      hibernate:
        ddl-auto: none
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true
      database: mysql
      properties:
        hibernate:
          format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  server:
    port: 8082